### ISSUE TITLE
Bad visibility of the fixes branch

### ISSUE THREAD

**Issue by ktnr** [sassoftware/cvrpsep#3]
I visited the repo before but haven't noticed the availability of the fixes branch because it is not the default branch. Can you consider making it the default branch and locking the original implementation in a separate branch?

Thank you for contributing fixes!

**Comment by mgalati13** [comment]
Yes. You are correct. Sorry for the confusion. I have merged branch fixes back into main and updated the ReadMe. I think we can just use main directly from now on unless there is a major change we want to track at a feature branch.

Your changes should now be at main (the default).

Thanks for the contribution!
